//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Home {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string WelcomeTo {
            get {
                return ResourceManager.GetString("WelcomeTo", resourceCulture);
            }
        }
        
        public static string AreaGreeting {
            get {
                return ResourceManager.GetString("AreaGreeting", resourceCulture);
            }
        }
        
        public static string WhatIsThisHeading {
            get {
                return ResourceManager.GetString("WhatIsThisHeading", resourceCulture);
            }
        }
        
        public static string WhatIsThisBody {
            get {
                return ResourceManager.GetString("WhatIsThisBody", resourceCulture);
            }
        }
        
        public static string WhatIs531Heading {
            get {
                return ResourceManager.GetString("WhatIs531Heading", resourceCulture);
            }
        }
        
        public static string WhatIs531Body {
            get {
                return ResourceManager.GetString("WhatIs531Body", resourceCulture);
            }
        }
        
        public static string NeedHelpHeading {
            get {
                return ResourceManager.GetString("NeedHelpHeading", resourceCulture);
            }
        }
        
        public static string ApiDocLinkText {
            get {
                return ResourceManager.GetString("ApiDocLinkText", resourceCulture);
            }
        }
        
        public static string GitLinkText {
            get {
                return ResourceManager.GetString("GitLinkText", resourceCulture);
            }
        }
    }
}
